name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: npm install  # Change this for your package manager
    
    - name: Run tests
      run: npm test  # Change this for your test command
    
    - name: Build project
      run: npm run build  # Change this for your build command

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.AWS_EC2_SSH_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'ENDSSH'
          cd /var/www/your-project
          git pull origin main
          npm install --production
          npm run build
          sudo systemctl restart nginx
        ENDSSH