name: Deploy to EC2

on:
  push:
    branches: [ main ]  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Create .env file for Vite
        run: |
          echo "VITE_NODE_URL=${{ secrets.REACT_APP_NODE_URL }}" > .env

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

      - name: Upload build folder to EC2
        run: |
          scp -r dist ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/cicd

      - name: Restart PM2 (optional backend or static server)
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/cicd
            # If you're using serve, uncomment below:
            # pm2 restart vite-app || pm2 start npx --name "vite-app" -- serve -s dist -l 3000
            # If you're using Nginx, you don’t need pm2
          EOF
